/**
 * Core abstraction for simulated integrations.
 *
 * Integration sims provide fake Slack channels, email inboxes, calendar events, etc.
 * for use during evals and demo mode. They inject context into the agent's prompt
 * and capture agent actions directed at the integration.
 *
 * Response modes:
 * - "deterministic": Scripted responses from a predefined list
 * - "llm-automated": Another LLM plays the other side (not yet implemented)
 */

export type IntegrationType = "slack" | "email" | "discord" | "telegram" | "calendar";

/**
 * A message or event visible to the agent within a simulated integration.
 */
export interface SimMessage {
  id: string;
  from: string;
  content: string;
  timestamp: string;
  /** Slack/Discord channel name */
  channel?: string;
  /** Email subject */
  subject?: string;
  /** Whether the agent has "seen" this message */
  read?: boolean;
  /** Arbitrary metadata */
  metadata?: Record<string, unknown>;
}

/**
 * An event that can be injected into the sim at a specific point in the eval.
 */
export interface SimEvent {
  /** What kind of event */
  type: "incoming_message" | "reaction" | "mention" | "calendar_event";
  /** The message/event data */
  data: SimMessage;
  /** When to inject this event */
  trigger:
    | { afterMessageIndex: number }
    | { afterSessionIndex: number }
    | "immediate";
}

/**
 * Describes how the sim generates responses to agent actions.
 */
export type ResponseMode =
  | { type: "deterministic"; responses: SimMessage[] }
  | { type: "llm-automated"; systemPrompt: string; model?: string };

/**
 * Configuration for setting up an integration sim.
 */
export interface IntegrationSimConfig {
  type: IntegrationType;
  /** Display name, e.g. "work-slack" or "personal-email" */
  name: string;
  /** How the sim generates replies to agent actions */
  responseMode: ResponseMode;
  /** Pre-populated messages (inbox, channel history, etc.) */
  initialMessages: SimMessage[];
  /** Events that trigger during the eval */
  scheduledEvents?: SimEvent[];
}

/**
 * An action the agent performed on an integration (parsed from agent response).
 */
export interface SimAction {
  type: "send_message" | "reply" | "react" | "schedule" | "search";
  integration: IntegrationType;
  integrationName: string;
  content: string;
  /** Target channel, email address, etc. */
  target?: string;
  /** Reference to a message being replied to */
  replyTo?: string;
}

/**
 * Result of processing an agent action.
 */
export interface SimActionResult {
  success: boolean;
  /** Response message generated by the sim (if any) */
  response?: SimMessage;
  /** Human-readable description of what happened */
  description: string;
}

/**
 * Core interface for a simulated integration.
 */
export interface IntegrationSim {
  readonly type: IntegrationType;
  readonly name: string;
  readonly config: IntegrationSimConfig;

  /**
   * Get text to inject into the agent's prompt describing current integration state.
   * E.g., "You have 3 unread Slack messages in #general: ..."
   */
  getContextInjection(): string;

  /**
   * Process an action the agent attempted on this integration.
   * Returns the result including any simulated response.
   */
  handleAction(action: SimAction): SimActionResult;

  /**
   * Inject a scheduled event (e.g., an incoming message arriving mid-eval).
   */
  injectEvent(event: SimEvent): void;

  /**
   * Get all messages in the sim (read + unread).
   */
  getMessages(): SimMessage[];

  /**
   * Get the full action log (everything the agent did on this integration).
   */
  getActionLog(): Array<{ action: SimAction; result: SimActionResult; timestamp: string }>;

  /**
   * Reset to initial state (for new eval runs).
   */
  reset(): void;

  /**
   * Process scheduled events that should fire at the given eval progress point.
   */
  processScheduledEvents(context: { messageIndex: number; sessionIndex: number }): void;
}
